const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const config=window.BC_CONFIG||{},db=config.url&&config.key?supabase.createClient(config.url,config.key):null;
const money=n=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND'}).format(n);
let products=[],orders=[],page=0;const labels={new:'Mới',confirmed:'Đã xác nhận',shipping:'Đang giao',done:'Hoàn thành',cancelled:'Đã hủy'};
function status(s){$('#admin-status').textContent=s}
function renderProducts(){const term=$('#search').value.toLowerCase();$('#product-list').innerHTML=products.filter(p=>p.name.toLowerCase().includes(term)).map(p=>`<article class="rounded-xl border bg-white p-5"><h3 class="font-bold">${esc(p.name)}</h3><p class="mt-2">${money(p.price)} · ${esc(p.unit)}</p><p class="mt-2">Tồn kho: ${p.stock} · ${p.active?'Đang bán':'Đã ẩn'}</p><button data-edit="${esc(p.id)}" class="mt-4">Sửa sản phẩm</button></article>`).join('')||'<p>Chưa có sản phẩm.</p>'}
function renderOrders(){const filter=$('#order-filter').value;$('#order-list').innerHTML=orders.filter(o=>filter==='all'||o.status===filter).map(o=>`<article class="rounded-xl border bg-white p-5"><div class="flex flex-wrap justify-between gap-3"><strong>Đơn ${esc(o.id)}</strong><span>${esc(new Date(o.created_at).toLocaleString('vi-VN'))}</span></div><p class="mt-3">${esc(o.customer_name)} · <a href="tel:${esc(o.phone)}">${esc(o.phone)}</a></p><p class="mt-2">${o.delivery==='ship'?'Giao tại: '+esc(o.address):'Nhận tại cửa hàng'}</p><p class="mt-2 whitespace-pre-line">Ghi chú: ${esc(o.note)||'Không'}</p><ul class="my-4 space-y-2">${(o.bc_order_items||[]).map(i=>`<li>${esc(i.name)} (${esc(i.unit)}) × ${i.quantity}: ${money(i.price*i.quantity)}</li>`).join('')}</ul><strong>Tạm tính ${money(o.total)} (chưa gồm phí giao)</strong><p class="mt-3">Trạng thái: ${labels[o.status]}</p>${['done','cancelled'].includes(o.status)?'':`<label for="state-${esc(o.id)}">Đổi trạng thái</label><select id="state-${esc(o.id)}"><option value="${o.status}">${labels[o.status]}</option>${({new:['confirmed','cancelled'],confirmed:['shipping','done','cancelled'],shipping:['done','cancelled']}[o.status]||[]).map(s=>`<option value="${s}">${labels[s]}</option>`).join('')}</select><button data-order="${esc(o.id)}" class="mt-3">Cập nhật</button>`}</article>`).join('')||'<p>Chưa có đơn trong danh sách đã tải.</p>'}
async function loadProducts(){const {data,error}=await db.from('bc_products').select('*').order('name');if(error)throw error;products=data;renderProducts()}
async function loadOrders(reset=true){if(reset){page=0;orders=[]}const {data,error}=await db.from('bc_orders').select('*,bc_order_items(*)').order('created_at',{ascending:false}).range(page*50,page*50+49);if(error)throw error;orders.push(...data);page++;$('#more-orders').hidden=data.length<50;renderOrders()}
async function load(){try{await loadProducts();await loadOrders();await loadBanner();status('Dữ liệu đã cập nhật.')}catch(e){status('Không tải được dữ liệu: '+e.message)}}
async function session(){if(!db){status('Điền Project URL và Publishable/anon key trong config.js trước.');$('#login-button').disabled=true;return}const {data,error}=await db.auth.getSession();if(error)return status(error.message);const logged=!!data.session;let admin=false;if(logged){const r=await db.rpc('bc_is_admin');admin=!!r.data&&!r.error}$('#login').hidden=logged&&admin;$('#dashboard').hidden=!admin;if(logged&&!admin){status('Tài khoản chưa được cấp quyền trong bc_admins.');await db.auth.signOut()}else if(admin)await load()}
$('#login').onsubmit=async e=>{e.preventDefault();if(!db)return;$('#login-button').disabled=true;try{const {error}=await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)throw error;$('#password').value='';await session()}catch(e){status(e.message)}finally{$('#login-button').disabled=false}};
$('#logout').onclick=async()=>{await db.auth.signOut();products=[];orders=[];$('#product-list').innerHTML='';$('#order-list').innerHTML='';await session();status('Đã đăng xuất.')};$('#reload').onclick=load;$('#more-orders').onclick=async()=>{try{await loadOrders(false)}catch(e){status(e.message)}};
$('#search').oninput=renderProducts;$('#order-filter').onchange=renderOrders;
const form=$('#product-form');
function editor(p){form.reset();$('#product-files').value='';$('#upload-status').textContent='';for(const key of ['id','name','price','stock','unit','description','ingredients','shelf_life'])form.elements[key].value=p?.[key]??(['price','stock'].includes(key)?0:'');form.elements.images.value=(p?.images||[]).join('\n');form.elements.active.checked=p?.active??true;form.elements.hot.checked=p?.hot??false;$('#editor-status').textContent='';previewProducts();$('#editor').showModal()}
$('#new-product').onclick=()=>editor();$('#editor-close').onclick=()=>{if(!uploading)$('#editor').close()};$('#editor').addEventListener('cancel',e=>{if(uploading)e.preventDefault()});
form.onsubmit=async e=>{e.preventDefault();if(uploading)return;$('#product-save').disabled=true;try{const f=form.elements;const images=f.images.value.split('\n').map(s=>s.trim()).filter(Boolean);if(images.some(s=>{try{return !/^https?:$/.test(new URL(s,location.href).protocol)}catch{return true}}))throw new Error('Đường dẫn ảnh không hợp lệ.');const row={name:f.name.value.trim(),price:Number(f.price.value),stock:Number(f.stock.value),unit:f.unit.value,description:f.description.value,ingredients:f.ingredients.value,shelf_life:f.shelf_life.value,images,active:f.active.checked,hot:f.hot.checked};const id=f.id.value;let result;if(id){const original=products.find(p=>p.id===id);result=await db.from('bc_products').update(row).eq('id',id).eq('stock',original.stock).select('id');if(!result.error&&!result.data.length)throw new Error('Tồn kho vừa thay đổi do đơn hàng mới. Đóng form, tải lại dữ liệu rồi sửa.')}else result=await db.from('bc_products').insert(row);if(result.error)throw result.error;await loadProducts();$('#editor').close();status('Đã lưu sản phẩm.')}catch(e){$('#editor-status').textContent=e.message}finally{$('#product-save').disabled=false}};
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit)editor(products.find(p=>p.id===b.dataset.edit));if(b.dataset.order){b.disabled=true;try{const value=document.getElementById('state-'+b.dataset.order).value;const {error}=await db.rpc('bc_update_order',{p_order:b.dataset.order,p_status:value});if(error)throw error;await load();status('Đã cập nhật đơn. Đơn hủy được hoàn tồn kho.')}catch(e){status(e.message)}finally{b.disabled=false}}});

// Ảnh được lưu trong bucket bc-images với tên duy nhất để tránh cache ảnh cũ.
let uploading=false,bannerObjectURL=null;
const mimeExtensions={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};
function checkFile(file){if(!mimeExtensions[file.type])throw new Error('Chỉ nhận JPG, PNG hoặc WEBP.');if(file.size>5*1024*1024)throw new Error('Ảnh '+file.name+' lớn hơn 5 MB.');if(!file.size)throw new Error('File ảnh đang trống.')}
async function uploadFile(file,folder){checkFile(file);const path=folder+'/'+crypto.randomUUID()+'.'+mimeExtensions[file.type];const bucket=db.storage.from('bc-images');const {error}=await bucket.upload(path,file,{contentType:file.type,cacheControl:'31536000',upsert:false});if(error)throw error;const {data}=bucket.getPublicUrl(path);return data.publicUrl}
function safeImage(url){try{const u=new URL(url,location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}}
function previewProducts(){const urls=form.elements.images.value.split('\n').map(s=>s.trim()).filter(Boolean);$('#product-preview').innerHTML=urls.map((url,i)=>`<div class="rounded-lg border p-1"><img src="${esc(safeImage(url))}" alt="Ảnh sản phẩm ${i+1}" class="aspect-square w-full rounded object-cover"><button type="button" data-remove-image="${i}" class="mt-1 w-full text-xs">Bỏ ảnh</button>${i===0?'<p class="text-center text-xs">Ảnh chính</p>':''}</div>`).join('')}
form.elements.images.addEventListener('input',previewProducts);
$('#product-preview').addEventListener('click',e=>{const b=e.target.closest('[data-remove-image]');if(!b||uploading)return;const urls=form.elements.images.value.split('\n').map(s=>s.trim()).filter(Boolean);urls.splice(Number(b.dataset.removeImage),1);form.elements.images.value=urls.join('\n');previewProducts()});
$('#product-files').addEventListener('change',async e=>{const files=Array.from(e.target.files);if(!files.length)return;try{files.forEach(checkFile)}catch(err){$('#upload-status').textContent=err.message;e.target.value='';return}uploading=true;$('#product-save').disabled=true;$('#product-files').disabled=true;$('#editor-close').disabled=true;let count=0;try{for(const file of files){$('#upload-status').textContent='Đang tải ảnh '+(count+1)+'/'+files.length+'…';const url=await uploadFile(file,'products');const current=form.elements.images.value.trim();form.elements.images.value=(current?current+'\n':'')+url;count++;previewProducts()}$('#upload-status').textContent='Đã tải '+count+' ảnh. Bấm Lưu sản phẩm để áp dụng.'}catch(err){$('#upload-status').textContent='Đã tải '+count+' ảnh. Lỗi: '+err.message+' — kiểm tra đã chạy upload-anh.sql.'}finally{uploading=false;$('#product-save').disabled=false;$('#product-files').disabled=false;$('#editor-close').disabled=false;e.target.value=''}});
async function loadBanner(){try{const {data,error}=await db.from('bc_settings').select('hero_image').eq('id','main').maybeSingle();if(error)throw error;if(data?.hero_image){$('#banner-preview').src=safeImage(data.hero_image);$('#banner-preview').hidden=false}$('#banner-status').textContent=''}catch{$('#banner-status').textContent='Chạy upload-anh.sql để kích hoạt tải ảnh và banner.'}}
$('#banner-file').addEventListener('change',e=>{const file=e.target.files[0];$('#banner-save').disabled=true;if(!file)return;try{checkFile(file);if(bannerObjectURL)URL.revokeObjectURL(bannerObjectURL);bannerObjectURL=URL.createObjectURL(file);$('#banner-preview').src=bannerObjectURL;$('#banner-preview').hidden=false;$('#banner-save').disabled=false;$('#banner-status').textContent='Ảnh xem trước. Bấm Lưu banner để áp dụng.'}catch(err){$('#banner-status').textContent=err.message;e.target.value=''}});
$('#banner-save').onclick=async()=>{const file=$('#banner-file').files[0];if(!file)return;$('#banner-save').disabled=true;$('#banner-file').disabled=true;$('#banner-status').textContent='Đang tải và lưu banner…';try{const url=await uploadFile(file,'banners');const {error}=await db.from('bc_settings').upsert({id:'main',hero_image:url});if(error)throw error;$('#banner-preview').src=url;$('#banner-file').value='';if(bannerObjectURL){URL.revokeObjectURL(bannerObjectURL);bannerObjectURL=null}$('#banner-status').textContent='Đã lưu banner. Tải lại trang chủ để xem ảnh mới.'}catch(err){$('#banner-status').textContent='Chưa lưu được banner: '+err.message;$('#banner-save').disabled=false}finally{$('#banner-file').disabled=false}};
session();
