const SB_URL="https://nfdovcuvgdmdhynhuhxy.supabase.co";
const SB_KEY="sb_publishable_g4fa73qmE0k9nd9TUNTlpg_88X1DgfV";
const PHONE="0985868317";
const db=window.supabase.createClient(SB_URL,SB_KEY);
let allProducts=[],filter="all";
let cart=JSON.parse(localStorage.getItem("nn_cart")||"[]");
const $=s=>document.querySelector(s);
const money=n=>Number(n||0).toLocaleString("vi-VN")+"₫";
const safe=s=>{const d=document.createElement("div");d.textContent=String(s??"");return d.innerHTML};
function category(p){const t=(p.ten||"").toLowerCase();if(t.includes("mochi"))return"mochi";if(t.includes("xu xê")||t.includes("phu thê"))return"xu-xe";if(t.includes("ô mai")||t.includes("o mai"))return"o-mai";if(t.includes("cốm tươi")||t.includes("cốm khô"))return"com";if(t.includes("bánh cốm"))return"banh-com";return"other"}
async function loadProducts(){const{data,error}=await db.from("san_pham").select("*").eq("dang_ban",true);if(error){$("#products").innerHTML=$("#bestProducts").innerHTML="<p>Chưa tải được sản phẩm.</p>";return}allProducts=(data||[]).sort((a,b)=>(b.noi_bat===true)-(a.noi_bat===true)||(Number(a.thu_tu_hot)||999)-(Number(b.thu_tu_hot)||999));renderAll();renderCart()}
function oldPrice(p){return Number(p.gia_cu||p.gia_goc||0)}
function discount(p){const old=oldPrice(p),price=Number(p.gia||0);return old>price&&price>0?Math.round((old-price)*100/old):0}
function card(p,prefix){const key=prefix+"-"+p.id,off=discount(p);return `<article class="product"><button class="product-view" type="button" data-view-id="${safe(p.id)}"><div class="product-image"><img src="${safe(p.anh_url||"feature.jpg")}" alt="${safe(p.ten)}" loading="lazy">${off?`<span class="sale">-${off}%</span>`:p.noi_bat?'<span class="hot">BÁN CHẠY</span>':""}</div><h3>${safe(p.ten)}</h3></button>${p.quy_cach?`<p class="packing">${safe(p.quy_cach)}</p>`:""}<div class="description-wrap"><p class="desc" id="desc-${key}">${safe(p.mo_ta||"Sản phẩm làm mới trong ngày, phù hợp thưởng thức và làm quà.")}</p><button class="desc-toggle" data-desc="desc-${key}">Xem thêm</button></div><div class="product-foot">${oldPrice(p)>Number(p.gia||0)?`<del>${money(oldPrice(p))}</del>`:""}<span class="price">${money(p.gia)}</span></div><button class="add-to-cart" type="button" data-product-id="${safe(p.id)}">CHỌN MUA</button></article>`}
function saveCart(){localStorage.setItem("nn_cart",JSON.stringify(cart))}
function cartQty(){return cart.reduce((sum,item)=>sum+item.quantity,0)}
function cartTotal(){return cart.reduce((sum,item)=>sum+item.price*item.quantity,0)}
function addToCart(id){const product=allProducts.find(p=>String(p.id)===String(id));if(!product)return;const item=cart.find(i=>String(i.id)===String(id));if(item)item.quantity+=1;else cart.push({id:product.id,name:product.ten,price:Number(product.gia||0),image:product.anh_url||"feature.jpg",quantity:1});saveCart();renderCart();showNotice(`Đã thêm ${product.ten} vào giỏ hàng`)}
function changeQuantity(id,amount){const item=cart.find(i=>String(i.id)===String(id));if(!item)return;item.quantity+=amount;if(item.quantity<=0)cart=cart.filter(i=>String(i.id)!==String(id));saveCart();renderCart()}
function renderCart(){const count=cartQty();$("#cartCount").textContent=count;$("#bottomCartCount").textContent=`(${count})`;$("#cartTotal").textContent=money(cartTotal());$("#cartItems").innerHTML=cart.length?cart.map(item=>`<article class="cart-row"><img src="${safe(item.image)}" alt="${safe(item.name)}"><div><strong>${safe(item.name)}</strong><p>${money(item.price)}</p><button class="remove-item" type="button" data-remove="${safe(item.id)}">Xóa</button></div><div class="cart-controls"><button type="button" data-minus="${safe(item.id)}">−</button><span>${item.quantity}</span><button type="button" data-plus="${safe(item.id)}">+</button></div></article>`).join(""):"<div class=\"empty-cart\">Giỏ hàng đang trống.<br>Hãy chọn bánh bạn muốn mua.</div>";document.querySelectorAll("[data-minus]").forEach(b=>b.onclick=()=>changeQuantity(b.dataset.minus,-1));document.querySelectorAll("[data-plus]").forEach(b=>b.onclick=()=>changeQuantity(b.dataset.plus,1));document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{cart=cart.filter(i=>String(i.id)!==String(b.dataset.remove));saveCart();renderCart()})}
const cartDrawer=$("#cartDrawer"),cartBackdrop=$("#cartBackdrop");
function setCart(open){cartDrawer.classList.toggle("show",open);cartBackdrop.classList.toggle("show",open);cartDrawer.setAttribute("aria-hidden",String(!open));document.body.classList.toggle("modal-open",open);if(open)renderCart()}
$("#cartOpen").onclick=()=>setCart(true);$("#bottomCartOpen").onclick=()=>setCart(true);$("#guideCartOpen").onclick=()=>setCart(true);$("#heroCartOpen").onclick=()=>setCart(true);$("#cartClose").onclick=()=>setCart(false);cartBackdrop.onclick=()=>setCart(false);
let detailProduct=null;
const detailModal=$("#detailModal");
function detailImages(product){const extra=Array.isArray(product.anh_phu)?product.anh_phu:[];const images=[product.anh_url,...extra,product.anh_phu_1,product.anh_phu_2,product.anh_phu_3].filter(Boolean);return [...new Set(images.length?images:["feature.jpg"])]}
function showDetail(id){const p=allProducts.find(item=>String(item.id)===String(id));if(!p)return;detailProduct=p;const images=detailImages(p);$("#detailImage").src=images[0];$("#detailImage").alt=p.ten||"Sản phẩm";$("#detailName").textContent=p.ten||"Sản phẩm";$("#detailPrice").textContent=money(p.gia);$("#detailOldPrice").textContent=oldPrice(p)>Number(p.gia||0)?money(oldPrice(p)):"";$("#detailDescription").textContent=p.mo_ta||"Sản phẩm được làm mới trong ngày, hương vị truyền thống, thích hợp để thưởng thức và làm quà.";$("#detailCategory").textContent=`Danh mục: ${p.quy_cach||"Đặc sản Hà Nội"}`;$("#detailQuantity").value=1;$("#detailThumbs").innerHTML=images.map((src,i)=>`<button class="${i===0?"active":""}" type="button" data-detail-image="${safe(src)}"><img src="${safe(src)}" alt="Ảnh ${i+1} của ${safe(p.ten)}"></button>`).join("");document.querySelectorAll("[data-detail-image]").forEach(button=>button.onclick=()=>{document.querySelectorAll("[data-detail-image]").forEach(x=>x.classList.remove("active"));button.classList.add("active");$("#detailImage").src=button.dataset.detailImage});detailModal.classList.add("show");detailModal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open")}
function closeDetail(){detailModal.classList.remove("show");detailModal.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open")}
$("#detailClose").onclick=closeDetail;detailModal.onclick=event=>{if(event.target===detailModal)closeDetail()};$("#detailMinus").onclick=()=>{$("#detailQuantity").value=Math.max(1,Number($("#detailQuantity").value||1)-1)};$("#detailPlus").onclick=()=>{$("#detailQuantity").value=Math.max(1,Number($("#detailQuantity").value||1)+1)};$("#detailAdd").onclick=()=>{if(!detailProduct)return;const quantity=Math.max(1,Number($("#detailQuantity").value||1));for(let i=0;i<quantity;i++)addToCart(detailProduct.id);closeDetail();setCart(true)};
function makeOrderCode(){return"NN"+Date.now().toString().slice(-8)}
$("#checkout").addEventListener("submit",async event=>{event.preventDefault();const status=$("#orderMessage"),submit=$("#checkoutSubmit");if(!cart.length){status.className="error";status.textContent="Giỏ hàng đang trống.";return}const name=$("#customerName").value.trim(),phone=$("#customerPhone").value.replace(/\s/g,""),address=$("#customerAddress").value.trim(),note=$("#customerNote").value.trim();if(!/^0\d{9}$/.test(phone)){status.className="error";status.textContent="Vui lòng nhập số điện thoại gồm 10 số.";return}const code=makeOrderCode(),total=cartTotal(),items=cart.map(i=>({id:i.id,ten:i.name,gia:i.price,soLuong:i.quantity,anh_url:i.image}));submit.disabled=true;submit.textContent="ĐANG LƯU ĐƠN…";status.className="";status.textContent="";const{error}=await db.from("don_hang").insert({ma_don:code,ten_khach_hang:name,so_dien_thoai:phone,dia_chi:address,ghi_chu:note||"Đặt trực tiếp trên website",san_pham:items,tong_tien:total,trang_thai:"moi"});submit.disabled=false;submit.textContent="ĐẶT HÀNG NGAY";if(error){status.className="error";status.textContent="Chưa đặt được hàng. Vui lòng kiểm tra mạng hoặc gọi 0985 868 317 để được hỗ trợ.";return}status.className="success order-success";status.innerHTML=`<strong>ĐẶT HÀNG THÀNH CÔNG!</strong><br>Mã đơn của bạn: <b>${code}</b><br>Cửa hàng sẽ gọi xác nhận sớm nhất.`;cart=[];saveCart();renderCart();event.target.reset()});
const mobileMenu=$("#mobileMenu"),menuBackdrop=$("#menuBackdrop"),menuOpen=$("#menuOpen");
function setMenu(open){mobileMenu.classList.toggle("show",open);menuBackdrop.classList.toggle("show",open);mobileMenu.setAttribute("aria-hidden",String(!open));menuOpen.setAttribute("aria-expanded",String(open));document.body.classList.toggle("menu-open",open)}
menuOpen.onclick=()=>setMenu(true);$("#menuClose").onclick=()=>setMenu(false);menuBackdrop.onclick=()=>setMenu(false);mobileMenu.querySelectorAll("a").forEach(link=>link.onclick=()=>setMenu(false));document.addEventListener("keydown",event=>{if(event.key==="Escape"){setMenu(false);setCart(false);closeDetail()}});
const heroSlider=$("#heroSlider"),heroSlides=[...document.querySelectorAll(".hero-slide")],heroDots=[...document.querySelectorAll(".hero-dots button")];let heroIndex=0,heroTimer,touchStartX=0;
function showHero(index){heroIndex=(index+heroSlides.length)%heroSlides.length;heroSlides.forEach((slide,i)=>slide.classList.toggle("active",i===heroIndex));heroDots.forEach((dot,i)=>dot.classList.toggle("active",i===heroIndex))}
function startHero(){clearInterval(heroTimer);heroTimer=setInterval(()=>showHero(heroIndex+1),4500)}
$(".hero-prev").onclick=()=>{showHero(heroIndex-1);startHero()};$(".hero-next").onclick=()=>{showHero(heroIndex+1);startHero()};heroDots.forEach((dot,index)=>dot.onclick=()=>{showHero(index);startHero()});heroSlider.addEventListener("touchstart",event=>{touchStartX=event.changedTouches[0].clientX},{passive:true});heroSlider.addEventListener("touchend",event=>{const distance=event.changedTouches[0].clientX-touchStartX;if(Math.abs(distance)>45){showHero(heroIndex+(distance<0?1:-1));startHero()}},{passive:true});heroSlider.onmouseenter=()=>clearInterval(heroTimer);heroSlider.onmouseleave=startHero;document.addEventListener("visibilitychange",()=>document.hidden?clearInterval(heroTimer):startHero());startHero();
function showNotice(message){let notice=document.getElementById("zaloNotice");if(!notice){notice=document.createElement("div");notice.id="zaloNotice";notice.setAttribute("role","status");document.body.appendChild(notice)}notice.textContent=message;notice.classList.add("show");clearTimeout(showNotice.timer);showNotice.timer=setTimeout(()=>notice.classList.remove("show"),2600)}
function renderAll(){const q=$("#search").value.trim().toLowerCase(),visible=allProducts.filter(p=>(filter==="all"||category(p)===filter)&&(p.ten||"").toLowerCase().includes(q)),hot=allProducts.filter(p=>p.noi_bat===true).slice(0,6),best=hot.length?hot:allProducts.slice(0,6);$("#bestProducts").innerHTML=best.length?best.map(p=>card(p,"best")).join(""):"<p>Chưa có sản phẩm nổi bật.</p>";$("#products").innerHTML=visible.length?visible.map(p=>card(p,"all")).join(""):"<p>Không tìm thấy sản phẩm.</p>";document.querySelectorAll(".desc-toggle").forEach(b=>b.onclick=()=>{const d=document.getElementById(b.dataset.desc),open=d.classList.toggle("open");b.textContent=open?"Thu gọn":"Xem thêm"});document.querySelectorAll(".add-to-cart").forEach(b=>b.onclick=()=>addToCart(b.dataset.productId));document.querySelectorAll("[data-view-id]").forEach(b=>b.onclick=()=>showDetail(b.dataset.viewId))}
$("#search").oninput=renderAll;document.querySelectorAll("#filters button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;renderAll()});$("#heroSlider").after($("#best"));renderCart();loadProducts();
