const supabaseDonHang=window.supabase.createClient("https://nfdovcuvgdmdhynhuhxy.supabase.co","sb_publishable_g4fa73qmE0k9nd9TUNTlpg_88X1DgfV");
const khuDangNhap=document.getElementById("khu-dang-nhap"),khuDonHang=document.getElementById("khu-don-hang"),danhSach=document.getElementById("danh-sach-don");let tatCaDon=[];
const tien=n=>Number(n||0).toLocaleString("vi-VN")+"₫";const sach=s=>{const d=document.createElement("div");d.textContent=String(s??"");return d.innerHTML};
function hienTrang(daDangNhap){khuDangNhap.classList.toggle("an",daDangNhap);khuDonHang.classList.toggle("an",!daDangNhap);document.getElementById("nut-dang-xuat").classList.toggle("an",!daDangNhap);if(daDangNhap)taiDon();}
document.getElementById("form-dang-nhap").addEventListener("submit",async e=>{e.preventDefault();const{error}=await supabaseDonHang.auth.signInWithPassword({email:document.getElementById("email-admin").value.trim(),password:document.getElementById("mat-khau-admin").value});if(error){document.getElementById("loi-dang-nhap").textContent="Email hoặc mật khẩu chưa đúng.";return}hienTrang(true)});
document.getElementById("nut-dang-xuat").addEventListener("click",async()=>{await supabaseDonHang.auth.signOut();hienTrang(false)});
async function taiDon(){danhSach.innerHTML="<p>Đang tải đơn hàng…</p>";const{data,error}=await supabaseDonHang.from("don_hang").select("*").order("ngay_tao",{ascending:false});if(error){danhSach.innerHTML="<p>Không tải được đơn. Hãy kiểm tra quyền quản trị trong Supabase.</p>";return}tatCaDon=data||[];hienDon();}
function hienDon(){const q=document.getElementById("tim-don").value.toLowerCase(),loc=document.getElementById("loc-trang-thai").value;const ds=tatCaDon.filter(d=>(loc==="tat-ca"||d.trang_thai===loc)&&[d.ma_don,d.ten_khach_hang,d.so_dien_thoai].join(" ").toLowerCase().includes(q));document.getElementById("dem-don-moi").textContent=tatCaDon.filter(d=>d.trang_thai==="moi").length;document.getElementById("dem-dang-xu-ly").textContent=tatCaDon.filter(d=>["da_xac_nhan","dang_giao"].includes(d.trang_thai)).length;document.getElementById("dem-hoan-thanh").textContent=tatCaDon.filter(d=>d.trang_thai==="hoan_thanh").length;if(!ds.length){danhSach.innerHTML="<p>Chưa có đơn hàng phù hợp.</p>";return}danhSach.innerHTML=ds.map(d=>`<article class="don"><div class="dong-dau"><div><span class="ma-don">${sach(d.ma_don)}</span><div class="ngay">${new Date(d.ngay_tao).toLocaleString("vi-VN")}</div></div><a class="goi-khach" href="tel:${sach(d.so_dien_thoai)}">Gọi khách</a></div><div class="thong-tin"><span><b>Khách:</b> ${sach(d.ten_khach_hang)}</span><span><b>SĐT:</b> ${sach(d.so_dien_thoai)}</span><span><b>Địa chỉ:</b> ${sach(d.dia_chi)}</span><span><b>Ghi chú:</b> ${sach(d.ghi_chu||"Không có")}</span></div><div class="san-pham">${(d.san_pham||[]).map(p=>`<div><span>${sach(p.ten)} × ${Number(p.soLuong||0)}</span><b>${tien(Number(p.gia||0)*Number(p.soLuong||0))}</b></div>`).join("")}</div><div class="chan-don"><span class="tong">Tổng: ${tien(d.tong_tien)}</span><select class="trang-thai" data-id="${d.id}"><option value="moi" ${d.trang_thai==="moi"?"selected":""}>Đơn mới</option><option value="da_xac_nhan" ${d.trang_thai==="da_xac_nhan"?"selected":""}>Đã xác nhận</option><option value="dang_giao" ${d.trang_thai==="dang_giao"?"selected":""}>Đang giao</option><option value="hoan_thanh" ${d.trang_thai==="hoan_thanh"?"selected":""}>Hoàn thành</option><option value="da_huy" ${d.trang_thai==="da_huy"?"selected":""}>Đã hủy</option></select></div></article>`).join("");document.querySelectorAll(".trang-thai").forEach(o=>o.addEventListener("change",async()=>{o.disabled=true;const{error}=await supabaseDonHang.from("don_hang").update({trang_thai:o.value}).eq("id",o.dataset.id);o.disabled=false;if(error)alert("Chưa cập nhật được trạng thái.");else{const d=tatCaDon.find(x=>String(x.id)===String(o.dataset.id));if(d)d.trang_thai=o.value;hienDon()}}));}
document.getElementById("tim-don").addEventListener("input",hienDon);document.getElementById("loc-trang-thai").addEventListener("change",hienDon);document.getElementById("nut-tai-lai").addEventListener("click",taiDon);supabaseDonHang.auth.getSession().then(({data})=>hienTrang(Boolean(data.session)));
