/* Cửa hàng, giỏ hàng và đặt đơn trực tiếp */
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND'}).format(n);
const config=window.BC_CONFIG||{};
const db=config.url&&config.key?window.supabase.createClient(config.url,config.key):null;
let products=[],basket={};try{const raw=JSON.parse(localStorage.getItem('bc-cart-v2')||'{}');for(const [id,q] of Object.entries(raw))if(Number.isInteger(q)&&q>0&&q<=99)basket[id]=q}catch{}
let ready=false,pending=null;
function msg(text){$('#store-message').textContent=text}
function imageURL(value){try{const u=new URL(value,location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}}
function save(){try{localStorage.setItem('bc-cart-v2',JSON.stringify(basket))}catch{}}
function add(id,q=1){const p=products.find(p=>p.id===id);if(!p||p.stock<1)return msg('Sản phẩm đã hết hàng.');basket[id]=Math.min(p.stock,99,(basket[id]||0)+q);save();renderCart();msg('Đã thêm '+p.name+' vào giỏ hàng.');pending=null}
function renderProducts(){const keyword=($('#product-search')?.value||'').toLocaleLowerCase('vi');$('#products').innerHTML=products.filter(p=>p.name.toLocaleLowerCase('vi').includes(keyword)).map(p=>`<article class="overflow-hidden rounded-xl border border-com/20 bg-white"><a href="chi-tiet.html?id=${encodeURIComponent(p.id)}"><img src="${esc(imageURL(p.images?.[0]))}" alt="${esc(p.name)}" width="800" height="600" class="aspect-[4/3] w-full object-cover" loading="lazy"></a><div class="p-5"><h3 class="font-serif text-2xl text-com"><a href="chi-tiet.html?id=${encodeURIComponent(p.id)}">${esc(p.name)}</a></h3><p class="mt-2 text-sm text-ink/70">${esc(p.unit)}</p><p class="mt-3 text-xl font-bold text-red">${money(p.price)}</p><p class="mt-2 text-sm">${p.stock>0?'Còn '+p.stock+' sản phẩm':'Hết hàng'}</p><div class="mt-4 grid grid-cols-2 gap-3"><button data-add="${esc(p.id)}" ${p.stock?'':'disabled'} class="min-h-12 rounded-lg border border-com px-2 text-sm font-bold text-com">Thêm vào giỏ</button><button data-buy="${esc(p.id)}" ${p.stock?'':'disabled'} class="min-h-12 rounded-lg bg-red px-2 text-sm font-bold text-white">Mua ngay</button></div></div></article>`).join('')||'<p>Chưa có sản phẩm phù hợp.</p>';fallbackImages()}
function fallbackImages(){document.querySelectorAll('img').forEach(img=>{if(img.dataset.fallback)return;img.dataset.fallback='1';img.addEventListener('error',()=>{img.src='images/banh-com.jpg'},{once:true})})}
function renderCart(){let total=0,count=0;const rows=Object.entries(basket);$('#cart-items').innerHTML=rows.map(([id,q])=>{const p=products.find(p=>p.id===id);count+=q;if(!p)return `<div class="py-3">Sản phẩm không còn bán <button data-remove="${esc(id)}" class="text-red">Xóa</button></div>`;total+=p.price*q;return `<div class="border-b py-4"><div class="flex justify-between gap-3"><strong>${esc(p.name)}</strong><span>${money(p.price*q)}</span></div><p class="mt-1 text-xs">${esc(p.unit)} · ${q>p.stock?'Vượt tồn kho, vui lòng giảm số lượng':'Còn '+p.stock}</p><div class="mt-3 flex items-center gap-3"><button data-minus="${esc(id)}" class="h-11 w-11 rounded border" aria-label="Giảm số lượng">−</button><span>${q}</span><button data-plus="${esc(id)}" class="h-11 w-11 rounded border" aria-label="Tăng số lượng">+</button><button data-remove="${esc(id)}" class="ml-auto min-h-11 text-red">Xóa</button></div></div>`}).join('')||'<p class="py-6">Giỏ hàng đang trống.</p>';$('#cart-count').textContent=count;$('#cart-total').textContent=money(total);$('#checkout-open').disabled=!ready||!count||rows.some(([id,q])=>{const p=products.find(p=>p.id===id);return !p||q>p.stock});$('#checkout-total').textContent=money(total)}
async function load(){if(!db){msg('Chưa kết nối kho sản phẩm. Cần điền Project URL và Publishable/anon key vào config.js.');renderCart();return}try{const {data,error}=await db.from('bc_products').select('*').eq('active',true).order('hot',{ascending:false}).order('name');if(error)throw error;products=data;ready=true;if($('#products'))renderProducts();if($('#detail-content'))renderDetail();renderCart();msg('')}catch(e){ready=false;msg('Không tải được kho sản phẩm. Kiểm tra kết nối và cấu hình Supabase.');renderCart()}}
function renderDetail(){const id=new URLSearchParams(location.search).get('id')||'banh-com';const p=products.find(p=>p.id===id);if(!p){$('#detail-content').innerHTML='<p>Sản phẩm không còn bán. <a href="index.html#san-pham">Trở về cửa hàng</a></p>';return}document.title=p.name+' — Nguyên Ninh';$('#detail-content').innerHTML=`<div><img id="detail-image" src="${esc(imageURL(p.images?.[0]))}" alt="${esc(p.name)}" class="aspect-square w-full rounded-xl object-cover"><div class="mt-4 grid grid-cols-3 gap-3">${(p.images||[]).map((url,i)=>`<button data-photo="${i}" aria-label="Xem ảnh ${i+1}" aria-pressed="${i===0}" class="overflow-hidden rounded-lg border-2 ${i===0?'border-com':'border-transparent'}"><img src="${esc(imageURL(url))}" alt="" class="aspect-square w-full object-cover"></button>`).join('')}</div></div><div><h1 class="font-serif text-4xl text-com">${esc(p.name)}</h1><p class="mt-5 text-3xl font-bold text-red">${money(p.price)}</p><p class="mt-2 text-sm">${esc(p.unit)} · Còn ${p.stock}</p><p class="mt-5 whitespace-pre-line leading-7">${esc(p.description)}</p><dl class="mt-5 space-y-3 rounded-xl border p-5"><dt class="font-bold">Thành phần</dt><dd>${esc(p.ingredients)||'Xem trên bao bì sản phẩm.'}</dd><dt class="font-bold">Hạn sử dụng / bảo quản</dt><dd>${esc(p.shelf_life)||'Xem trên bao bì sản phẩm.'}</dd></dl><label for="detail-qty" class="mt-5 block font-semibold">Số lượng</label><div class="mt-3 flex items-center gap-3"><button id="detail-minus" class="h-12 w-12 rounded border">−</button><input id="detail-qty" type="number" min="1" max="${Math.min(p.stock,99)||1}" value="1" class="h-12 w-16 rounded border text-center"><button id="detail-plus" class="h-12 w-12 rounded border">+</button></div><div class="mt-5 grid grid-cols-2 gap-3"><button id="detail-add" ${p.stock?'':'disabled'} class="min-h-12 rounded-lg border border-com text-com">Thêm vào giỏ</button><button id="detail-buy" ${p.stock?'':'disabled'} class="min-h-12 rounded-lg bg-red font-bold text-white">Đặt hàng ngay</button></div></div>`;const q=$('#detail-qty');$('#detail-minus').onclick=()=>q.value=Math.max(1,(Number(q.value)||1)-1);$('#detail-plus').onclick=()=>q.value=Math.min(99,p.stock,(Number(q.value)||1)+1);const doAdd=()=>{if(!q.reportValidity())return false;add(p.id,Number(q.value));return true};$('#detail-add').onclick=doAdd;$('#detail-buy').onclick=()=>{if(doAdd())$('#cart').showModal()};document.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>{$('#detail-image').src=imageURL(p.images[Number(b.dataset.photo)]);document.querySelectorAll('[data-photo]').forEach(x=>{const active=x===b;x.setAttribute('aria-pressed',String(active));x.classList.toggle('border-com',active);x.classList.toggle('border-transparent',!active)})});fallbackImages()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.add)add(b.dataset.add);if(b.dataset.buy){add(b.dataset.buy);$('#cart').showModal()}if(b.dataset.plus)add(b.dataset.plus);if(b.dataset.minus){if(--basket[b.dataset.minus]<=0)delete basket[b.dataset.minus];pending=null;save();renderCart()}if(b.dataset.remove){delete basket[b.dataset.remove];pending=null;save();renderCart()}});
$('#cart-open').onclick=()=>$('#cart').showModal();$('#cart-close').onclick=()=>$('#cart').close();$('#checkout-close').onclick=()=>$('#checkout').close();$('#checkout-open').onclick=()=>{$('#cart').close();$('#checkout').showModal()};
$('#delivery').onchange=()=>{const ship=$('#delivery').value==='ship';$('#address-row').hidden=!ship;$('#address').required=ship};
const form=$('#checkout-form');let sending=false;
form.addEventListener('input',()=>{pending=null;$('#phone').setCustomValidity('');$('#fullname').setCustomValidity('');$('#address').setCustomValidity('')});
form.onsubmit=async e=>{e.preventDefault();if(sending)return;if(!db||!ready)return msg('Kho sản phẩm chưa kết nối.');const phone=$('#phone').value.replace(/[\s().-]/g,'').replace(/^\+84/,'0');$('#phone').setCustomValidity(/^0[35789]\d{8}$/.test(phone)?'':'Nhập số di động Việt Nam hợp lệ.');$('#fullname').setCustomValidity($('#fullname').value.trim()?'':'Nhập họ tên.');$('#address').setCustomValidity($('#delivery').value==='ship'&&!$('#address').value.trim()?'Nhập địa chỉ nhận hàng.':'');if(!form.reportValidity())return;if(!Object.keys(basket).length)return;pending ||= crypto.randomUUID();sending=true;$('#submit-order').disabled=true;$('#order-status').textContent='Đang gửi đơn…';try{const {data,error}=await db.rpc('bc_place_order',{p_request:pending,p_name:$('#fullname').value.trim(),p_phone:phone,p_address:$('#delivery').value==='ship'?$('#address').value.trim():'',p_delivery:$('#delivery').value,p_note:$('#note').value.trim(),p_items:Object.entries(basket).map(([id,quantity])=>({id,quantity}))});if(error)throw error;basket={};save();pending=null;renderCart();form.reset();$('#delivery').dispatchEvent(new Event('change'));$('#order-status').textContent=`Đã lưu đơn ${data.order_id}. Tạm tính ${money(data.total)}. Cửa hàng sẽ liên hệ xác nhận phí giao và thời gian nhận. Thanh toán khi nhận hàng.`;await load()}catch(e){$('#order-status').textContent=e.message?.includes('BC:')?e.message.split('BC:')[1]:'Chưa xác nhận được kết quả. Nhấn Gửi đơn lại để kiểm tra cùng đơn, tránh tạo trùng.'}finally{sending=false;$('#submit-order').disabled=false}};
if($('#product-search'))$('#product-search').oninput=renderProducts;
if($('#menu-toggle'))$('#menu-toggle').onclick=()=>{const menu=$('#mobile-menu');menu.hidden=!menu.hidden;$('#menu-toggle').setAttribute('aria-expanded',String(!menu.hidden))};
load();
