create table if not exists public.don_hang (
    id bigint generated by default as identity primary key,
    ma_don text not null unique,
    ten_khach_hang text not null,
    so_dien_thoai text not null,
    dia_chi text not null,
    ghi_chu text,
    san_pham jsonb not null,
    tong_tien numeric not null default 0,
    trang_thai text not null default 'moi',
    ngay_tao timestamptz not null default now()
);

alter table public.don_hang enable row level security;

drop policy if exists "Khach duoc tao don hang" on public.don_hang;
create policy "Khach duoc tao don hang"
on public.don_hang
for insert
to anon, authenticated
with check (true);
